"""Go2 trajectory tracking environment — JAX/MJX vectorized.

Pure JAX functions for reset, step, reward, termination. All JIT-compatible.
Replaces the CPU gymnasium env with GPU-accelerated MJX physics.

Observation (39D): body_pos(3) + body_quat(4) + joints(12) + body_vel(6) + joint_vel(12) + phase(2)
Action (12D): residual joint position corrections
Actuation: PD controller + J^T·F feedforward
Reward: Additive weighted sum of 5 Gaussian terms (OPT-Mimic Eq. 15-16)
"""

from __future__ import annotations

from typing import Any, NamedTuple

import jax
import jax.numpy as jnp
import mujoco
import mujoco.mjx as mjx
import numpy as np

from .reference import ReferenceTrajectory


# ---------------------------------------------------------------------------
# Constants (same as original CPU env, adapted for Go2)
# ---------------------------------------------------------------------------
KP = 25.0
KD = 1.5
# Per-joint torque limits from Go2 actuator ctrlrange (hip/thigh=23.7, calf=45.43)
TORQUE_LIMITS = np.array([
    23.7, 23.7, 45.43,  # FL: hip, thigh, calf
    23.7, 23.7, 45.43,  # FR
    23.7, 23.7, 45.43,  # RL
    23.7, 23.7, 45.43,  # RR
], dtype=np.float32)
ACTION_LIMIT = 0.2

SIGMA_POS = 0.10
SIGMA_ORI = 0.25
SIGMA_JOINT = 0.5
SIGMA_SMOOTH = 1.0
SIGMA_TORQUE = 40.0

W_POS = 0.3
W_ORI = 0.3
W_JOINT = 0.2
W_SMOOTH = 0.1
W_TORQUE = 0.1

TERM_MULTIPLIER = 2.5
OBS_DIM = 39
N_SUBSTEPS = 20  # 50Hz policy / 1kHz physics
CONTACT_GRACE_WINDOW = 12  # 240ms at 50Hz
FOOT_GEOM_NAMES = ("FL", "FR", "RL", "RR")


# ---------------------------------------------------------------------------
# Data containers
# ---------------------------------------------------------------------------

class EnvState(NamedTuple):
    mjx_data: Any  # mjx.Data
    phase: jnp.ndarray  # int32 scalar
    prev_action: jnp.ndarray  # (12,)
    last_torque: jnp.ndarray  # (12,)
    first_step: jnp.ndarray  # bool scalar
    joint_offset: jnp.ndarray  # (12,)
    torque_scale: jnp.ndarray  # float32 scalar
    done: jnp.ndarray  # bool scalar


class RefData(NamedTuple):
    body_pos: jnp.ndarray  # (N+1, 3)
    body_quat: jnp.ndarray  # (N+1, 4)
    joint_pos: jnp.ndarray  # (N+1, 12)
    joint_vel: jnp.ndarray  # (N, 12)
    body_vel: jnp.ndarray  # (N+1, 3)
    body_ang_vel: jnp.ndarray  # (N+1, 3)
    ff_torques: jnp.ndarray  # (N, 12)
    max_phase: jnp.ndarray  # int32 scalar
    contact_sequence: jnp.ndarray  # (4, N) — 1=stance, 0=swing, -1=unavailable
    ground_geom_id: jnp.ndarray  # int32 scalar
    foot_geom_ids: jnp.ndarray  # (4,) int32
    near_transition: jnp.ndarray  # (4, N) — 1.0 if near contact transition


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

_XML_PATH = None  # set by load_mjx_model


def _find_xml_path() -> str:
    """Find the go2-flat.xml generated by gym_quadruped."""
    import gym_quadruped
    from pathlib import Path
    pkg = Path(gym_quadruped.__file__).parent
    xml = pkg / "utils" / "mujoco" / "assets" / "go2-flat.xml"
    if xml.exists():
        return str(xml)
    # Fallback: generate it via QuadrupedEnv
    from gym_quadruped.quadruped_env import QuadrupedEnv
    env = QuadrupedEnv(robot="go2", scene="flat", sim_dt=0.001)
    env.close()
    assert xml.exists(), f"go2-flat.xml not found at {xml}"
    return str(xml)


def load_mjx_model(sim_dt: float = 0.001) -> tuple[mujoco.MjModel, Any]:
    """Load Go2 model, convert cylinders→capsules for MJX, return (mj_model, mjx_model)."""
    global _XML_PATH
    if _XML_PATH is None:
        _XML_PATH = _find_xml_path()

    mj_model = mujoco.MjModel.from_xml_path(_XML_PATH)
    mj_model.opt.timestep = sim_dt
    # MJX solver iterations: 6 is sufficient, higher values are catastrophically slow
    mj_model.opt.iterations = 6
    mj_model.opt.ls_iterations = 6
    # Increase contact damping to reduce landing bounce (o_solref = [timeconst, damping])
    mj_model.opt.o_solref[1] = 1.5

    # Convert collision cylinders to capsules (MJX doesn't support cylinder-box)
    for i in range(mj_model.ngeom):
        if mj_model.geom_contype[i] > 0 and mj_model.geom_type[i] == 5:
            mj_model.geom_type[i] = 3  # capsule

    mjx_model = mjx.put_model(mj_model)
    return mj_model, mjx_model


def _get_ground_geom_id(mj_model: mujoco.MjModel) -> int:
    """Get the ground geom ID (floor)."""
    gid = mujoco.mj_name2id(mj_model, mujoco.mjtObj.mjOBJ_GEOM, "floor")
    return int(gid)


def _get_foot_geom_ids(mj_model: mujoco.MjModel) -> np.ndarray:
    """Get foot geom IDs for FL, FR, RL, RR. Returns (4,) int32."""
    return np.array([
        mujoco.mj_name2id(mj_model, mujoco.mjtObj.mjOBJ_GEOM, name)
        for name in FOOT_GEOM_NAMES
    ], dtype=np.int32)


# ---------------------------------------------------------------------------
# Reference data conversion
# ---------------------------------------------------------------------------

def make_ref_data(ref: ReferenceTrajectory, mj_model: mujoco.MjModel) -> RefData:
    """Convert CPU ReferenceTrajectory to JAX RefData arrays."""
    N = ref.max_phase
    body_pos = np.zeros((N + 1, 3))
    body_quat = np.zeros((N + 1, 4))
    joint_pos = np.zeros((N + 1, 12))
    body_vel = np.zeros((N + 1, 3))
    body_ang_vel = np.zeros((N + 1, 3))

    for k in range(N + 1):
        body_pos[k] = ref.get_body_pos(k)
        body_quat[k] = ref.get_body_quat(k)
        joint_pos[k] = ref.get_joint_pos(k)
        body_vel[k] = ref.get_body_vel(k)
        body_ang_vel[k] = ref.get_body_ang_vel(k)

    joint_vel = np.zeros((N, 12))
    ff_torques = np.zeros((N, 12))
    for k in range(N):
        joint_vel[k] = ref.get_joint_vel(k)
        ff_torques[k] = ref.get_feedforward_torque(k)

    # Contact sequence: (4, N) with -1 sentinel when unavailable
    if ref.contact_sequence is not None:
        contact_sequence = ref.contact_sequence[:, :N].astype(np.float32)
    else:
        contact_sequence = -np.ones((4, N), dtype=np.float32)

    # Geom IDs for contact termination
    ground_geom_id = _get_ground_geom_id(mj_model)
    foot_geom_ids = _get_foot_geom_ids(mj_model)

    # Precompute near-transition mask for contact grace window (120ms)
    near_transition = np.ones((4, N), dtype=np.float32)  # default: all grace
    if ref.contact_sequence is not None:
        near_transition = np.zeros((4, N), dtype=np.float32)
        for foot in range(4):
            for k in range(N):
                current = ref.contact_sequence[foot, k]
                lo = max(0, k - CONTACT_GRACE_WINDOW)
                hi = min(N - 1, k + CONTACT_GRACE_WINDOW)
                if np.any(ref.contact_sequence[foot, lo:hi + 1] != current):
                    near_transition[foot, k] = 1.0

    return RefData(
        body_pos=jnp.array(body_pos),
        body_quat=jnp.array(body_quat),
        joint_pos=jnp.array(joint_pos),
        joint_vel=jnp.array(joint_vel),
        body_vel=jnp.array(body_vel),
        body_ang_vel=jnp.array(body_ang_vel),
        ff_torques=jnp.array(ff_torques),
        max_phase=jnp.int32(N),
        contact_sequence=jnp.array(contact_sequence),
        ground_geom_id=jnp.int32(ground_geom_id),
        foot_geom_ids=jnp.array(foot_geom_ids),
        near_transition=jnp.array(near_transition),
    )


# ---------------------------------------------------------------------------
# Core env functions (all JIT-compatible)
# ---------------------------------------------------------------------------

def _clamp_phase(phase: jnp.ndarray, max_phase: jnp.ndarray) -> jnp.ndarray:
    return jnp.clip(phase, 0, max_phase - 1)


def _quat_error(q_ref: jnp.ndarray, q_actual: jnp.ndarray) -> jnp.ndarray:
    """Quaternion error: vector part of q_ref * q_actual^{-1}. Returns (3,)."""
    q_inv = jnp.array([q_actual[0], -q_actual[1], -q_actual[2], -q_actual[3]])
    w1, x1, y1, z1 = q_ref[0], q_ref[1], q_ref[2], q_ref[3]
    w2, x2, y2, z2 = q_inv[0], q_inv[1], q_inv[2], q_inv[3]
    return jnp.array([
        w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
        w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
        w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2,
    ])


def get_obs(state: EnvState, ref_data: RefData) -> jnp.ndarray:
    """Build 39D observation: sensor(37) + phase(2)."""
    data = state.mjx_data
    phase = _clamp_phase(state.phase, ref_data.max_phase)

    body_pos = data.qpos[0:3]
    body_quat = data.qpos[3:7]
    joint_pos = data.qpos[7:19] + state.joint_offset
    body_vel = data.qvel[0:3]
    body_ang_vel = data.qvel[3:6]
    joint_vel = data.qvel[6:18]

    angle = 2.0 * jnp.pi * phase / ref_data.max_phase
    phase_enc = jnp.array([jnp.cos(angle), jnp.sin(angle)])

    return jnp.concatenate([
        body_pos, body_quat, joint_pos,
        body_vel, body_ang_vel, joint_vel,
        phase_enc,
    ])


def compute_reward(
    state: EnvState, action: jnp.ndarray, ref_data: RefData
) -> tuple[jnp.ndarray, dict[str, jnp.ndarray]]:
    """Additive weighted sum of 5 Gaussian terms (OPT-Mimic Eq. 15)."""
    data = state.mjx_data
    phase = _clamp_phase(state.phase, ref_data.max_phase)

    ref_pos = ref_data.body_pos[phase]
    ref_quat = ref_data.body_quat[phase]
    ref_joint = ref_data.joint_pos[phase]

    pos_err_sq = jnp.sum((ref_pos - data.qpos[0:3]) ** 2)
    r_pos = jnp.exp(-pos_err_sq / (2.0 * SIGMA_POS**2))

    ori_err = _quat_error(ref_quat, data.qpos[3:7])
    ori_err_sq = jnp.sum(ori_err**2)
    r_ori = jnp.exp(-ori_err_sq / (2.0 * SIGMA_ORI**2))

    joint_err_sq = jnp.sum((ref_joint - data.qpos[7:19]) ** 2)
    r_joint = jnp.exp(-joint_err_sq / (2.0 * SIGMA_JOINT**2))

    rate_sq = jnp.sum((action - state.prev_action) ** 2)
    r_smooth = jnp.exp(-rate_sq / (2.0 * SIGMA_SMOOTH**2))

    max_torque = jnp.max(jnp.abs(state.last_torque))
    r_torque = jnp.exp(-(max_torque**2) / (2.0 * SIGMA_TORQUE**2))

    total = (
        W_POS * r_pos + W_ORI * r_ori + W_JOINT * r_joint
        + W_SMOOTH * r_smooth + W_TORQUE * r_torque
    )

    info = {
        "pos_error": jnp.sqrt(pos_err_sq),
        "ori_error": jnp.sqrt(ori_err_sq),
        "joint_error": jnp.sqrt(joint_err_sq),
        "action_rate": jnp.sqrt(rate_sq),
        "max_torque": max_torque,
        "rw_pos": r_pos,
        "rw_ori": r_ori,
        "rw_joint": r_joint,
        "rw_smooth": r_smooth,
        "rw_torque": r_torque,
    }
    return total, info


def check_termination(
    state: EnvState, reward_info: dict[str, jnp.ndarray],
    ref_data: RefData,
) -> tuple[jnp.ndarray, jnp.ndarray]:
    """Early termination per OPT-Mimic III-C.4:
    1. Any tracking error exceeds 2.5x sigma.
    2. Non-foot body touches ground.
    3. Foot contact mismatch with reference (120ms grace window).

    Returns (terminated: bool, reason: int32).
    Reason codes: 0=none, 1=threshold, 2=body_contact, 3=contact_mismatch, 4=nan.
    """
    thresh_pos = TERM_MULTIPLIER * SIGMA_POS
    thresh_ori = TERM_MULTIPLIER * SIGMA_ORI
    thresh_joint = TERM_MULTIPLIER * SIGMA_JOINT
    thresh_smooth = TERM_MULTIPLIER * SIGMA_SMOOTH
    thresh_torque = TERM_MULTIPLIER * SIGMA_TORQUE

    reason = jnp.int32(0)

    # Condition 1: tracking error thresholds
    thresh_hit = (
        (reward_info["pos_error"] > thresh_pos)
        | (reward_info["ori_error"] > thresh_ori)
        | (reward_info["joint_error"] > thresh_joint)
        | ((~state.first_step) & (reward_info["action_rate"] > thresh_smooth))
        | (reward_info["max_torque"] > thresh_torque)
    )
    reason = jnp.where(thresh_hit, jnp.int32(1), reason)

    # Condition 2: non-foot body ground contact
    contact = state.mjx_data.contact
    active = contact.dist <= 0  # (ncon,)
    g1_ground = contact.geom1 == ref_data.ground_geom_id
    g2_ground = contact.geom2 == ref_data.ground_geom_id
    involves_ground = (g1_ground | g2_ground) & active
    other_geom = jnp.where(g1_ground, contact.geom2, contact.geom1)
    is_foot = jnp.any(
        other_geom[:, None] == ref_data.foot_geom_ids[None, :], axis=1
    )  # (ncon,)
    non_foot_ground = jnp.any(involves_ground & ~is_foot)
    reason = jnp.where(non_foot_ground & (reason == 0), jnp.int32(2), reason)

    # Condition 3: foot contact mismatch with grace window
    phase = _clamp_phase(state.phase, ref_data.max_phase)
    ref_contact = ref_data.contact_sequence[:, phase]  # (4,)
    has_contact_info = ref_contact[0] >= 0  # -1 sentinel = unavailable
    foot_match = other_geom[:, None] == ref_data.foot_geom_ids[None, :]  # (ncon, 4)
    actual_contact = jnp.any(foot_match & involves_ground[:, None], axis=0)  # (4,)
    expected_contact = ref_contact > 0.5  # (4,) bool
    grace = ref_data.near_transition[:, phase]  # (4,) — 1.0 if near transition
    mismatch = (actual_contact != expected_contact) & (grace < 0.5)
    contact_mismatch = has_contact_info & jnp.any(mismatch)
    reason = jnp.where(contact_mismatch & (reason == 0), jnp.int32(3), reason)

    # NaN check (physics divergence)
    has_nan = jnp.any(jnp.isnan(state.mjx_data.qpos))
    reason = jnp.where(has_nan & (reason == 0), jnp.int32(4), reason)

    terminated = reason > 0
    return terminated, reason


def reset(
    rng: jnp.ndarray, mjx_model: Any, mj_model: mujoco.MjModel,
    ref_data: RefData, randomize: bool = True,
) -> EnvState:
    """Reset environment to reference state with domain randomization."""
    rng, rng_phase, rng_offset, rng_torque = jax.random.split(rng, 4)

    start_phase = jnp.where(
        randomize,
        jax.random.randint(rng_phase, (), 0, ref_data.max_phase),
        jnp.int32(0),
    )

    joint_offset = jnp.where(
        randomize,
        jax.random.normal(rng_offset, (12,)) * 0.02,
        jnp.zeros(12),
    )

    torque_scale = jnp.where(
        randomize,
        jnp.clip(1.0 + jax.random.normal(rng_torque, ()) * 0.1, 0.5, 1.5),
        jnp.float32(1.0),
    )

    phase = _clamp_phase(start_phase, ref_data.max_phase)

    # Build initial qpos/qvel from reference
    qpos = jnp.zeros(19)
    qpos = qpos.at[0:3].set(ref_data.body_pos[phase])
    qpos = qpos.at[3:7].set(ref_data.body_quat[phase])
    qpos = qpos.at[7:19].set(ref_data.joint_pos[phase])

    qvel = jnp.zeros(18)
    qvel = qvel.at[0:3].set(ref_data.body_vel[phase])
    qvel = qvel.at[3:6].set(ref_data.body_ang_vel[phase])
    vel_phase = _clamp_phase(start_phase, ref_data.max_phase)
    qvel = qvel.at[6:18].set(ref_data.joint_vel[vel_phase])

    # Create MJX data with reference state
    mj_data = mujoco.MjData(mj_model)
    mjx_data = mjx.put_data(mj_model, mj_data)
    mjx_data = mjx_data.replace(qpos=qpos, qvel=qvel)
    mjx_data = mjx.forward(mjx_model, mjx_data)

    return EnvState(
        mjx_data=mjx_data,
        phase=start_phase,
        prev_action=jnp.zeros(12),
        last_torque=jnp.zeros(12),
        first_step=jnp.bool_(True),
        joint_offset=joint_offset,
        torque_scale=torque_scale,
        done=jnp.bool_(False),
    )


def reset_fast(
    rng: jnp.ndarray, mjx_data_template: Any,
    ref_data: RefData, randomize: bool = True,
) -> EnvState:
    """Fast reset using existing mjx_data (no mj_model needed). For auto-reset in scan."""
    rng, rng_phase, rng_offset, rng_torque = jax.random.split(rng, 4)

    start_phase = jnp.where(
        randomize,
        jax.random.randint(rng_phase, (), 0, ref_data.max_phase),
        jnp.int32(0),
    )

    joint_offset = jnp.where(
        randomize,
        jax.random.normal(rng_offset, (12,)) * 0.02,
        jnp.zeros(12),
    )

    torque_scale = jnp.where(
        randomize,
        jnp.clip(1.0 + jax.random.normal(rng_torque, ()) * 0.1, 0.5, 1.5),
        jnp.float32(1.0),
    )

    phase = _clamp_phase(start_phase, ref_data.max_phase)

    qpos = jnp.zeros(19)
    qpos = qpos.at[0:3].set(ref_data.body_pos[phase])
    qpos = qpos.at[3:7].set(ref_data.body_quat[phase])
    qpos = qpos.at[7:19].set(ref_data.joint_pos[phase])

    qvel = jnp.zeros(18)
    qvel = qvel.at[0:3].set(ref_data.body_vel[phase])
    qvel = qvel.at[3:6].set(ref_data.body_ang_vel[phase])
    vel_phase = _clamp_phase(start_phase, ref_data.max_phase)
    qvel = qvel.at[6:18].set(ref_data.joint_vel[vel_phase])

    new_data = mjx_data_template.replace(
        qpos=qpos, qvel=qvel,
        ctrl=jnp.zeros(12),
        time=jnp.float32(0.0),
    )
    # Skip mjx.forward here — the next mjx.step in the scan body will
    # compute derived quantities. get_obs only needs qpos/qvel which are set.

    return EnvState(
        mjx_data=new_data,
        phase=start_phase,
        prev_action=jnp.zeros(12),
        last_torque=jnp.zeros(12),
        first_step=jnp.bool_(True),
        joint_offset=joint_offset,
        torque_scale=torque_scale,
        done=jnp.bool_(False),
    )


def step(
    state: EnvState, action: jnp.ndarray, mjx_model: Any,
    ref_data: RefData,
) -> tuple[EnvState, jnp.ndarray, jnp.ndarray, jnp.ndarray, dict]:
    """Step environment: apply PD+ff torque, substep physics, compute reward/done.

    Returns (new_state, obs, reward, done, reward_info).
    """
    # Scale action
    action = action * ACTION_LIMIT

    phase = _clamp_phase(state.phase, ref_data.max_phase)

    ref_joint_pos = ref_data.joint_pos[phase]
    ref_joint_vel = ref_data.joint_vel[phase]
    ff_torque = ref_data.ff_torques[phase]

    actual_joint_pos = state.mjx_data.qpos[7:19]
    actual_joint_vel = state.mjx_data.qvel[6:18]

    target_pos = ref_joint_pos + action + state.joint_offset
    torque = (
        KP * (target_pos - actual_joint_pos)
        + KD * (ref_joint_vel - actual_joint_vel)
        + ff_torque
    )
    torque = jnp.clip(torque, -jnp.array(TORQUE_LIMITS), jnp.array(TORQUE_LIMITS))
    torque = torque * state.torque_scale

    # Substep physics
    data = state.mjx_data.replace(ctrl=torque)

    def substep_fn(data, _):
        return mjx.step(mjx_model, data), None

    data, _ = jax.lax.scan(substep_fn, data, None, length=N_SUBSTEPS)

    new_state = EnvState(
        mjx_data=data,
        phase=state.phase + 1,
        prev_action=action,
        last_torque=torque,
        first_step=jnp.bool_(False),
        joint_offset=state.joint_offset,
        torque_scale=state.torque_scale,
        done=state.done,
    )

    reward, reward_info = compute_reward(new_state, action, ref_data)
    terminated, term_reason = check_termination(new_state, reward_info, ref_data)
    truncated = new_state.phase >= ref_data.max_phase

    done = terminated | truncated
    # Truncation = reason 5 (only if not already terminated)
    term_reason = jnp.where(truncated & ~terminated, jnp.int32(5), term_reason)
    reward_info["term_reason"] = term_reason.astype(jnp.float32)

    # Force reward to 0 if NaN
    reward = jnp.where(jnp.isnan(reward), 0.0, reward)

    new_state = new_state._replace(done=done)
    obs = get_obs(new_state, ref_data)

    # Replace NaN obs with 0
    obs = jnp.where(jnp.isnan(obs), 0.0, obs)

    return new_state, obs, reward, done, reward_info


# ---------------------------------------------------------------------------
# Batched (vmapped) env functions
# ---------------------------------------------------------------------------

def make_batched_fns(
    mjx_model: Any, ref_data: RefData,
):
    """Create batched (vmapped) reset and step functions.

    Returns (batched_reset, batched_step, batched_get_obs).
    """
    def _reset_single(rng, mjx_data_template):
        return reset_fast(rng, mjx_data_template, ref_data, randomize=True)

    def _step_single(state, action):
        return step(state, action, mjx_model, ref_data)

    def _get_obs_single(state):
        return get_obs(state, ref_data)

    batched_step = jax.vmap(_step_single)
    batched_get_obs = jax.vmap(_get_obs_single)

    return _reset_single, batched_step, batched_get_obs


# ---------------------------------------------------------------------------
# CPU env class (for evaluation rollout with rendering)
# ---------------------------------------------------------------------------

class Go2TrackingEnv:
    """CPU-based tracking env for evaluation/rendering. Matches JAX env exactly."""
    KP = KP
    KD = KD
    TORQUE_LIMITS = TORQUE_LIMITS
    ACTION_LIMIT = ACTION_LIMIT
    SIGMA_POS = SIGMA_POS
    SIGMA_ORI = SIGMA_ORI
    SIGMA_JOINT = SIGMA_JOINT
    SIGMA_SMOOTH = SIGMA_SMOOTH
    SIGMA_TORQUE = SIGMA_TORQUE
    W_POS = W_POS
    W_ORI = W_ORI
    W_JOINT = W_JOINT
    W_SMOOTH = W_SMOOTH
    W_TORQUE = W_TORQUE
    OBS_DIM = OBS_DIM

    def __init__(self, ref: ReferenceTrajectory, sim_dt: float = 0.001,
                 control_dt: float = 0.02, randomize: bool = False):
        self.ref = ref
        self.sim_dt = sim_dt
        self.control_dt = control_dt
        self.substeps = int(control_dt / sim_dt)
        self.randomize = randomize

        from gym_quadruped.quadruped_env import QuadrupedEnv
        self._quad_env = QuadrupedEnv(
            robot="go2", scene="flat",
            ground_friction_coeff=0.8,
            state_obs_names=QuadrupedEnv._DEFAULT_OBS + ("contact_forces:base",),
            sim_dt=sim_dt,
        )
        self._phase = 0
        self._prev_action = np.zeros(12)
        self._last_torque = np.zeros(12)
        self._joint_offset = np.zeros(12)
        self._torque_scale = 1.0
        self._first_step = True

    @property
    def mjModel(self):
        return self._quad_env.mjModel

    @property
    def mjData(self):
        return self._quad_env.mjData

    def reset(self):
        self._joint_offset = np.zeros(12)
        self._torque_scale = 1.0
        start_phase = 0

        init_qpos = np.zeros(19)
        init_qpos[0:3] = self.ref.get_body_pos(start_phase)
        init_qpos[3:7] = self.ref.get_body_quat(start_phase)
        init_qpos[7:19] = self.ref.get_joint_pos(start_phase)

        init_qvel = np.zeros(18)
        init_qvel[0:3] = self.ref.get_body_vel(start_phase)
        init_qvel[3:6] = self.ref.get_body_ang_vel(start_phase)
        init_qvel[6:18] = self.ref.get_joint_vel(start_phase)

        self._quad_env.reset(qpos=init_qpos, qvel=init_qvel)
        self._phase = start_phase
        self._prev_action = np.zeros(12)
        self._last_torque = np.zeros(12)
        self._first_step = True
        return self._build_obs()

    def step(self, action: np.ndarray):
        action = action * self.ACTION_LIMIT
        ref_joint_pos = self.ref.get_joint_pos(self._phase)
        ref_joint_vel = self.ref.get_joint_vel(self._phase)
        ff_torque = self.ref.get_feedforward_torque(self._phase)

        sim_obs = self._quad_env._get_obs()
        actual_joint_pos = sim_obs["qpos"][7:19]
        actual_joint_vel = sim_obs["qvel"][6:18]

        target_pos = ref_joint_pos + action + self._joint_offset
        torque = (
            self.KP * (target_pos - actual_joint_pos)
            + self.KD * (ref_joint_vel - actual_joint_vel)
            + ff_torque
        )
        torque = np.clip(torque, -self.TORQUE_LIMITS, self.TORQUE_LIMITS)
        torque = torque * self._torque_scale
        self._last_torque = torque.copy()

        for _ in range(self.substeps):
            sim_obs, _, _, _, _ = self._quad_env.step(action=torque)

        reward, info = self._compute_reward(sim_obs, action)
        self._first_step = False
        self._phase += 1
        truncated = self._phase >= self.ref.max_phase
        self._prev_action = action.copy()
        obs = self._build_obs()
        return obs, reward, False, truncated, {"phase": self._phase, **info}

    def _build_obs(self):
        sim_obs = self._quad_env._get_obs()
        sensor = np.concatenate([
            sim_obs["qpos"][0:3], sim_obs["qpos"][3:7],
            sim_obs["qpos"][7:19] + self._joint_offset,
            sim_obs["qvel"][0:6], sim_obs["qvel"][6:18],
        ])
        angle = 2.0 * np.pi * self._phase / self.ref.max_phase
        phase_enc = np.array([np.cos(angle), np.sin(angle)])
        return np.concatenate([sensor, phase_enc]).astype(np.float32)

    def _compute_reward(self, sim_obs, action):
        qpos = sim_obs["qpos"]
        pos_err_sq = np.sum((self.ref.get_body_pos(self._phase) - qpos[0:3]) ** 2)
        r_pos = np.exp(-pos_err_sq / (2.0 * self.SIGMA_POS**2))

        q_ref = self.ref.get_body_quat(self._phase)
        q_act = qpos[3:7]
        q_inv = np.array([q_act[0], -q_act[1], -q_act[2], -q_act[3]])
        w1, x1, y1, z1 = q_ref
        w2, x2, y2, z2 = q_inv
        ori_err = np.array([
            w1*x2 + x1*w2 + y1*z2 - z1*y2,
            w1*y2 - x1*z2 + y1*w2 + z1*x2,
            w1*z2 + x1*y2 - y1*x2 + z1*w2,
        ])
        ori_err_sq = np.sum(ori_err**2)
        r_ori = np.exp(-ori_err_sq / (2.0 * self.SIGMA_ORI**2))

        joint_err_sq = np.sum((self.ref.get_joint_pos(self._phase) - qpos[7:19]) ** 2)
        r_joint = np.exp(-joint_err_sq / (2.0 * self.SIGMA_JOINT**2))

        rate_sq = np.sum((action - self._prev_action) ** 2)
        r_smooth = np.exp(-rate_sq / (2.0 * self.SIGMA_SMOOTH**2))

        max_torque = np.max(np.abs(self._last_torque))
        r_torque = np.exp(-(max_torque**2) / (2.0 * self.SIGMA_TORQUE**2))

        total = (
            self.W_POS * r_pos + self.W_ORI * r_ori + self.W_JOINT * r_joint
            + self.W_SMOOTH * r_smooth + self.W_TORQUE * r_torque
        )
        info = {
            "pos_error": np.sqrt(pos_err_sq), "ori_error": np.sqrt(ori_err_sq),
            "joint_error": np.sqrt(joint_err_sq), "action_rate": np.sqrt(rate_sq),
            "max_torque": max_torque,
            "rw_pos": float(r_pos), "rw_ori": float(r_ori), "rw_joint": float(r_joint),
            "rw_smooth": float(r_smooth), "rw_torque": float(r_torque),
        }
        return float(total), info

    def close(self):
        self._quad_env.close()
